### PR TITLE
Fixed csv export

### LINKED ISSUE #122: Exported CSV from organizers "judging" needs to have a header

### PR DESCRIPTION
**Pull request by abi-kothapalli**
Fixes N-W56 where exported CSV from organizers "judging" did not have any headers.

Closes #122

### CODE REVIEW

File: components/allScores.tsx [hunk 1]
```diff
@@ -60,7 +60,21 @@ const newCols = [
...
+		headers: [
+			'Technical Ability',
+			'Creativity',
+			'Utility',
+			'Presentation',
+			'Wow Factor',
+			'Comments',
+			'Feedback',
+			'Team',
+			'Judge',
```
Comment (Ace314159) [inline components/allScores.tsx:75]: This same list is duplicated in some other places too. I think it would be nice to have these be a constant somewhere. What do you think?

Comment (aadibajpai) [reply components/allScores.tsx:75]: I agree, otherwise we will have to maintain the list of fields in 2 places, ideally there is a programmatic way to get these from our models or so

Comment (aadibajpai) [reply components/allScores.tsx:75]: yeah looks like you can just make it from newCols at least
